version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node-backend
    restart: always
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: taxa
      DB_HOST: postgres
      DB_SCHEMA: inside
      DB_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '3001:3001'  # API HTTP
      - '3002:3002'  # WebSocket

  survey-dashboard:
    build:
      context: ./survey-dashboard
      dockerfile: Dockerfile
    container_name: react-survey-dashboard
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  pgdata:
